title: Arif | Portfolio
description: Personal website showcasing projects, background, and activities
baseurl: "" # set to repo name if using project pages, e.g., "/arif-portfolio"
url: "https://ar1f123.github.io"
markdown: kramdown
theme: none
